import { GenUIRenderer } from '@genui/react';
import { useChat } from '../hooks/useChat';
import { WIZARD_PROMPT } from '../prompts';
import { SpecViewer } from '../components/SpecViewer';

const WELCOME_SPEC = {
  genui: '1.0' as const,
  root: {
    type: 'stack' as const,
    gap: 'lg' as const,
    children: [
      {
        type: 'section' as const,
        title: 'Onboarding Wizard',
        description: 'Watch the LLM generate a multi-step onboarding flow — forms, validation, tabs, and state — from a single click.',
        children: [
          {
            type: 'card' as const,
            title: 'Welcome to Launchpad 🚀',
            description: "Let's get your workspace set up. This will only take a few minutes.",
            children: [
              {
                type: 'stack' as const,
                direction: 'horizontal' as const,
                gap: 'sm' as const,
                children: [
                  {
                    type: 'badge' as const,
                    label: '5 steps',
                    variant: 'default' as const,
                  },
                  {
                    type: 'badge' as const,
                    label: '~3 minutes',
                    variant: 'default' as const,
                  },
                ],
              },
            ],
          },
          {
            type: 'button' as const,
            label: 'Start onboarding →',
            variant: 'primary' as const,
            size: 'lg' as const,
            aria: { label: 'Start the onboarding wizard' },
            action: {
              type: 'llm' as const,
              payload: { intent: 'start-onboarding', step: 1 },
              context: 'none' as const,
            },
          },
        ],
      },
      {
        type: 'section' as const,
        title: 'What this demonstrates',
        children: [
          {
            type: 'accordion' as const,
            items: [
              {
                title: 'Multi-step forms generated dynamically',
                defaultOpen: true,
                children: [{
                  type: 'markdown' as const,
                  content: 'Each form step is generated by the LLM in response to the previous step\'s submission. The LLM tracks progress and advances through the flow, generating appropriate fields and validation rules each time.',
                }],
              },
              {
                title: 'Stateful context across turns',
                children: [{
                  type: 'markdown' as const,
                  content: 'Form submissions include `context: "spec"` — the LLM receives the current spec alongside the submitted data, so it can reference previous inputs in subsequent steps.',
                }],
              },
              {
                title: 'Client-side validation from spec',
                children: [{
                  type: 'markdown' as const,
                  content: 'Validation rules (`required`, `pattern`, `minLength`) are embedded in the spec. The renderer enforces them before the form can be submitted — no round-trip to the LLM for validation.',
                }],
              },
            ],
          },
        ],
      },
    ],
  },
};

interface WizardProps {
  apiKey: string;
}

export function Wizard({ apiKey }: WizardProps) {
  const { spec, status, error, handleAction, reset } = useChat({
    systemPrompt: WIZARD_PROMPT,
    apiKey,
  });

  const displaySpec = spec ?? WELCOME_SPEC;

  return (
    <div className="demo-layout demo-layout--centered">
      {/* Left panel */}
      <aside className="demo-sidebar">
        <div className="demo-sidebar-header">
          <h2 className="demo-sidebar-title">Onboarding Wizard</h2>
          <p className="demo-sidebar-desc">
            A multi-step onboarding flow generated entirely by the LLM — one spec per step.
            Each form submission triggers the next step.
          </p>
        </div>

        <div className="demo-sidebar-info">
          <div className="info-item">
            <span className="info-dot info-dot--blue" />
            <span>Step generated on demand</span>
          </div>
          <div className="info-item">
            <span className="info-dot info-dot--green" />
            <span>Validation in spec, enforced by renderer</span>
          </div>
          <div className="info-item">
            <span className="info-dot info-dot--purple" />
            <span>Previous data flows forward via context</span>
          </div>
        </div>

        {spec && (
          <button className="chat-reset" onClick={reset} style={{ marginTop: '1rem' }}>
            ↺ Start over
          </button>
        )}

        {error && <div className="demo-error" role="alert"><strong>Error:</strong> {error}</div>}

        <div className="demo-data-note">
          <p className="demo-data-note-label">🧙 System prompt</p>
          <p>The LLM knows the full 5-step onboarding flow for "Launchpad" SaaS and generates each form step in response to the previous submission.</p>
        </div>
      </aside>

      {/* Right panel */}
      <div className="demo-output">
        <div className="demo-output-header">
          <span className="demo-output-label">
            {status === 'loading'
              ? '⏳ Generating next step…'
              : spec
              ? '✓ Step rendered — fill the form and submit'
              : '← Click "Start onboarding" to begin'}
          </span>
        </div>

        <div className="demo-output-body">
          {status === 'loading' ? (
            <div className="demo-loading">
              <div className="demo-loading-ring" aria-hidden="true" />
              <span>Generating next step…</span>
            </div>
          ) : (
            <GenUIRenderer spec={displaySpec} onAction={handleAction} />
          )}
        </div>

        <SpecViewer spec={spec} />
      </div>
    </div>
  );
}
